version: '3.8'

services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wedding-countdown.rule=Host(`whenwillyoumarryme.cmzx.it`)"
      - "traefik.http.routers.wedding-countdown.entrypoints=websecure"
      - "traefik.http.routers.wedding-countdown.tls.certresolver=letsencrypt"
    networks:
      - open-oni_default

networks:
  traefik-network:
    external: true
